//to catch prefixes (including hyphenation): ((?:[\w\b\-]+)?...
//to catch suffixes (including hyphenation):                ...(?:\w|\-|\'|&#39;)*)
//for apostrophes: (?:\'|&#39;)
//for quotes: (?:\"|&quot;)


var zizekKeys = {
  "two sides of the same coin": /(two sides of the same coin)/ig,
  "the very moment": /(the very moment(?:\w|\-|\'|&#39;)*)/ig,
  "couple of years ago": /((?:a )?(?:couple|few|number)(?: of)? years (?:ago|back))/ig,
  "last but not least": /(last(?:[\s\,\-\—]*\w+?[\s\,\-\—])* least)/ig,
  "bear in mind": /(bear(?:\w|\-|\'|&#39;)*[\b\s]*in mind)/ig,
  "i would prefer not to": /((?:i )?(?:would )?prefer not to)/ig,
  "first thing to note": /((?:the )?first thing (?:to|(?:(?:i|we|you|one|he|she|they) (?:could|must|should|will|do))) note)/ig,
  "the wings of the dove": /((?:the )?wings of the dove)/ig,
  "exact same way": /((?:exactly|precisely) the same way|(?:the )?(?:exact|precise) same way)/ig,
  "end of the film": /((?:the )?end of the film)/ig,
  "discourse of the analyst": /((?:the )discourse of the analyst)/ig,
  "all we have to do": /(all (?:i|we|you|one|he|she|they) (?:have to|must) do)/ig,
  "not the same": /(not the same)/ig,
  "not forget": /((?:i |we |you |one |he |she |they )?(?:should |could |must |will |can ?)(?:not|never) forget)/ig,
  "object cause of desire": /((?:the )?object cause of (?:\s?\w+ )?desire)/ig,
  "french revolution": /((?:the )?french revolution(?:\w|\-|\'|&#39;)*(?:(?: of | in )(?:.+?48))?)/ig,
  "french": /(french|france)(?! revolution)/ig,
  "portrait of a lady": /((?:the )?portrait of a lady)/ig,
  "lacanian": /((?:[\w\b\-]+)?lacanian)/ig,
  "lacanese": /((?:[\w\b\-]+)?lacanese)/ig,
  "hegelian": /((?:[\w\b\-]+)?hegelian)/ig,
  "hegelese": /((?:[\w\b\-]+)?hegelese)/ig,
  "freudian": /((?:[\w\b\-]+)?freudian)/ig,
  "kantian": /((?:[\w\b\-]+)?kantian)/ig,
  "the thing": /([tT]he Thing|[dD]as Ding)/g,
  "the other": /([tT]he Other(?:\w|\-|\'|&#39;)*)/g,
  "precise sense": /((?:in )?(?:\s?\w+ )?precise sense)/ig,
  "very beginning": /((?:in |from |since )?(?:its |the )very beginnings?)/ig,
  "order of being": /(orders? of being)/ig,
  "the real": /([tT]he Real)/g,
  "very heart": /((?:at the )?very (?:heart|core))/ig,
  "same as": /((?:the )?same as)/ig,
  "time to time": /((?:from )?time to time)/ig,
  "it is crucial": /((?:it |this )?is crucial(?: to)?)/ig,
  "price to be paid": /((?:a |the )?price (?:\w+ )?(?:be )?paid)/ig,
  "the gap which separates": /((?:a |the |that |this )?gaps? (?:between|(?:\w+ )?separat(?:\w|\-|\'|&#39;)*))/ig,
  "and so on": /(and so (?:on|forth))/ig,
  "repressed": /((?:return of )?(?:the )?repress(?:\w|\-|\'|&#39;)*)/ig,
  "part of no part": /(parts?.of.no.part)/ig,
  "in other words": /(in other words)/ig,
  "the only way": /((?:the )?only ways?)/ig,
  "big other": /((?:the )?big others?)/ig,
  "paradox": /((?:a |the |that |this )?paradox(?:\w|\-|\'|&#39;)*)/ig,
  "symbolic order": /((?:a |the |that |this )?symbolic order(?:\w|\-|\'|&#39;)*)/ig,
  "symbolic": /(symbolic)(?! order)/ig,
  "universal": /((?:the )?universal(?:\w|\-|\'|&#39;)*)/ig,
  "the social": /(the social)(?!\w)/ig,
  "the human": /(the human)(?!\w)/ig,
  "his or her": /(his or her)/ig,
  "in this sense": /(in this sense)/ig,
  "way of life": /(ways? of (?:life|living))/ig,
  "more and more": /(more and more)/ig,
  "relationship between": /((?:a |the |that |this |in )?(?:relat|link)(?:\w|\-|\'|&#39;)*(?:\s?\w+ )? (?:between|among|to))/ig,
  "objet petit a": /(objets? petits?(?: a)?)/ig,
  "in both cases": /(in (?:all |both |these |this |that |every )cases?)/ig,
  "at its purest": /(at its purest)/ig,
  "first thing": /((?:the )?first thing)/ig,
  "in the middle": /(in the (?:middle|midst))/ig,
  "again and again": /(again and again)/ig,
  "for example": /((?:for |as an |as |few |some |these )examples?)/ig,
  "communist": /((?:[\w\b\-]+)?communi(?!t)(?:\w|\-|\'|&#39;)*)/ig,
  "fascist": /((?:[\w\b\-]+)?fasci(?!na)(?:\w|\-|\'|&#39;)*)/ig,
  "socialist": /((?:[\w\b\-]+)?socialis(?:\w|\-|\'|&#39;)*)/ig,
  "sublime": /((?:the )?sublime)/ig,
  "the subject": /(the subject(?:\'|&#39;|(?:\w|\-|\'|&#39;)*)?s?)/ig,
  "a priori": /(a priori)/ig,
  "antisemitism": /(anti.semit(?:\w|\-|\'|&#39;)*)/ig,
  "the west": /(the west|(?:the )?western)/ig,
  "the east": /(the east|(?:the )?eastern)/ig,
  "asian": /(asians?)/ig,
  "china": /(chin(?:a|ese))/ig,
  "japan": /(japan(?:\w|\-|\'|&#39;)*)/ig,
  "greece": /(greece|greeks?)/ig,
  "continental": /(continental)/ig,
  "europe": /(europe(?:\w|\-|\'|&#39;)*)/ig,
  //"america": /((?!south.|central.|latin.)america(?:\w|\-|\'|&#39;)*|united states)/ig,
  "enemy": /((?:the |our |his |her |this |that |their |my |your |one(?:\'|&#39;)s |other(?:\'|&#39;)s )?enemy)/ig,
  "in fact": /((?:in|the) facts?)(?!\w)/ig,
  "revolutionary terror": /(revolutionary terrors?)/ig,
  "definition": /(by definition)/ig,
  "stricto sensu": /(stricto sensu)/ig,
  "minimal difference": /(minimal differences?)/ig,
  "death drive": /((?:the )?(?:death drives?|trieb))/ig,
  "master signifier": /(master.signifiers?)/ig,
  "the master": /((?:the )?(?:discourse of )the master(?:(?:\'|&#39;)s discourse)?)/ig,
  "short circuit": /(short circuit(?:\w|\-|\'|&#39;)*)/ig,
  "transcendental": /(transcendental)/ig,
  "consciousness": /((?:self.)?consciousness)/ig,
  "soviet": /(soviets?(?: union)?)/ig,
  "stalin": /(stalin(?:is[tm]s?)?)/ig,
  "lenin": /(lenin(?:is[tm]s?)?)/ig,
  "marx": /(marx(?:is[tm]s?)?)/ig,
  "the matrix": /(the matrix|(?:the )?matrix(?: reloaded| revolutions?| trilogy| films?))/ig,
  "blade runner": /(blade runner)/ig,
  "noir": /(noirs?)/ig,
  "normal": /(normal(?:\w|\-|\'|&#39;)*)/ig,
  "labor": /(labou?r)/ig,
  "slave": /(slave(?:\w|\-|\'|&#39;)*)/ig,
  "imperial": /(imperial(?:\w|\-|\'|&#39;)*|empires?)/ig,
  "triad": /((?:this |that |the |basic )?triads?)/ig,
  "parsifal": /(parsifal(?:\w|\-|\'|&#39;)*)/ig,
  "excess": /(excess(?:\w|\-|\'|&#39;)*)/ig,
  "wagner": /(wagner(?:(?:\'|&#39;)s|ian)?)/ig,
  "lynch": /(Lynch(?:\w|\-|\'|&#39;)*)/g,
  "kafka": /(kafka(?:\w|\'|&#39;)*)/ig,
  "brazil": /(brazil(?:\w|\'|&#39;)*)/ig,
  "hitchcock": /(hitchcock(?:\w|\-|\'|&#39;)*)/ig,
  "christ": /((?:jesus )?(?:christ|jesus)(?:\-like| jesus|.figure|(?:\'|&#39;)s?)?)(?!ian)/ig,
  "god": /(God(?:(?:\'|&#39;)?s?|-like|-king))/g,
  "class": /((?:[\w\b\-]+)?class(?!ic)(?:\w|\-|\'|&#39;)*)/ig,
  "global": /((?:[\w\b\-]+)?global(?:\w|\-|\'|&#39;)*)(?! capital)/ig,
  "ideology": /((?:[\w\b\-]+)?ideolog(?:\w|\-|\'|&#39;)*)/ig,
  "capital": /((?:global |late )?(?:[\w\b\-]+)?capital(?:\w|\-|\'|&#39;)*)/ig,
  "superego": /(superego)/ig,
  "thanatos": /(thanatos)/ig,
  "pleasure principle": /((?:beyond )?(?:the )?pleasure principle)/ig,
  "joussaince": /((?:[\w\b\-]+)?joussaince)/ig,
  "history": /((?:[\w\b\-]+)?histor(?:\w|\-|\'|&#39;)*)/ig,
  "mother": /(mother(?:\w|\-|\'|&#39;)*)/ig,
  "father": /((?:[\w\b\-]+)?father(?:\w|\-|\'|&#39;)*)/ig,
  "analysand": /(analysands?)/ig,
  "anxiety": /(anxi(?:ety|ous))/ig,
  "jew": /((?:[\w\b\-]+)?jew(?!el)(?:\w|\-|\'|&#39;)*)/ig,
  "israel": /((?:[\w\b\-]+)?israel(?:\w|\-|\'|&#39;)*)/ig
};


module.exports.keys = zizekKeys;