//to catch prefixes (including hyphenation): ((?:[\w\b\-]+)?...
//to catch suffixes (including hyphenation):                ...(?:\w|\-|\'|&#39;)*)
//for apostrophes: (?:\'|&#39;)
//for quotes: (?:\"|&quot;)


var zizekKeys = {
  "two-sides-of-the-same-coin": /(two sides of the same coin)/ig,
  //"the-very-moment": /(the very moment(?:\w|\-|\'|&#39;)*)/ig,
  "couple-of-years-ago": /((?:a )?(?:couple|few|number)(?: of)? years (?:ago|back))/ig,
  "here-we-should": /(here(?: i| we| you| one| he| she| they) (?:could|must|should|will|do))/ig,
  "is-it-not": /(is it not(?: so| the case| true| here))/ig,
  "truth": /(truth(?:\w|\'|&#39;)*)/ig,
  "chesterton": /(chesterton(?:\w|\'|&#39;)*)/ig,
  "inverse": /((?:in|ob)vers(?:\w|\'|&#39;)*)/ig,
  "last-but-not-least": /(last(?:[\s\,\-\—]*\w+?[\s\,\-\—])* least)/ig,
  "on-the-other-hand": /(on the (?:(?:other |one )hand|contrary))/ig,
  "in-constrast": /((?:in |the |this )?contrast(?:\w|\'|&#39;)*)/ig,
  "bear-in-mind": /((?:bear|born)(?:\w|\-|\'|&#39;)*[\b\s]*in mind)/ig,
  "inscribe": /((?:[\w\b\-]+)?inscri[pb](?:\w|\'|&#39;)*)/ig,
  "i-would-prefer-not-to": /((?:i )?(?:would )?prefer not to)/ig,
  "sensible": /((?:[\w\b\-]+)?sensible(?:\w|\-|\'|&#39;)*)/ig,
  "first-thing": /((?:the )?first thing(?: to |(?:(?: i| we| you| one| he| she| they) (?:could|must|should|will|do)))?(?:note)?)/ig,
  "the-wings-of-the-dove": /((?:the )?wings of the dove)/ig,
  "exact-same-way": /((?:exactly|precisely) the same way|(?:the )?(?:exact|precise) same way)/ig,
  "end-of-the-film": /((?:the )?end of the film)/ig,
  "analyst": /((?:the )?(?:discourse of the )?analyst)/ig,
  "all-we-have-to-do": /(all (?:i|we|you|one|he|she|they) (?:have to|must) do)/ig,
  "not-the-same": /(not(?:[\s\,]*\w+?[\s\,]*)? the same)/ig,
  "cogito": /(cogit(?:\w|\-|\'|&#39;)*)/ig,
  "nothing": /(Nothing|[Nn]othingness)/g,
  "contract": /(contract(?:\w|\-|\'|&#39;)*)/ig,
  "speculative": /(speculati(?:\w|\-|\'|&#39;)*)/ig,
  "context": /(context(?:\w|\-|\'|&#39;)*)/ig,
  "world": /((?:[\w\b\-]+)?(?:world(?! war)|universe)(?:\w|\-|\'|&#39;)*)/ig,
  "regime": /(regime(?:\w|\'|&#39;)*)/ig,
  "inerval": /(interval(?:\w|\'|&#39;)*)/ig,
  "metaphysics": /(metaphysic(?:\w|\-|\'|&#39;)*)/ig,
  "subversion": /(subvers(?:\w|\-|\'|&#39;)*)/ig,
  "not-forget": /((?:i |we |you |one |he |she |they )?(?:should |could |must |will |can ?)(?:not|never) forget)/ig,
  "object-cause-of-desire": /((?:the )?object cause of (?:\s?\w+ )?desire)/ig,
  "french-revolution": /((?:the )?french revolution(?:\w|\-|\'|&#39;)*(?:(?: of | in )(?:.+?48))?)/ig,
  "french": /(french|france)(?! revolution)/ig,
  "portrait-of-a-lady": /((?:the )?portrait of a lady)/ig,
  "bentham": /(bentham(?:\w|\-|\'|&#39;)*)/ig,
  "benjamin": /(benjamin(?:\w|\-|\'|&#39;)*)/ig,
  "entity": /((?:[\w\b\-]+)?entit(?:y|ies))/ig,
  "leibniz": /(leibniz(?:\w|\-|\'|&#39;)*)/ig,
  "phenomena": /(phenomen(?:\w|\-|\'|&#39;)*)/ig,
  "lacan": /((?:[\w\b\-]+)?lacan(?:\w|\-|\'|&#39;)*)/ig,
  "hegel": /((?:[\w\b\-]+)?hegel(?:\w|\-|\'|&#39;)*)/ig,
  "freud": /((?:[\w\b\-]+)?freud(?:\w|\-|\'|&#39;)*)/ig,
  "fort-da": /(fort.da)/ig,
  "problematic": /((?:[\w\b\-]+)?problematic(?:\w|\-|\'|&#39;)*)/ig,
  "dialectic": /(dialectic(?:\w|\-|\'|&#39;)*)/ig,
  "kant": /((?:[\w\b\-]+)?kant(?:\w|\-|\'|&#39;)*)/ig,
  "jung": /((?:[\w\b\-]+)?jung(?:\w|\-|\'|&#39;)*)/ig,
  "radical": /(\bradical(?:\w|\-|\'|&#39;)*)/ig,
  "nature": /((?:[\w\b\-]+)?natur(?:e|al)(?:\w|\-|\'|&#39;)*)/ig,
  "culture": /((?:[\w\b\-]+)?cultur(?:\w|\-|\'|&#39;)*)/ig,
  "the-thing": /((?:[tT]he )?Thing|(?:[dD]as )?Ding)/g,
  "enigma": /(\benigma(?:\w|\-|\'|&#39;)*)/ig,
  "extreme": /((?:[\w\b\-]+)?extrem(?:\w|\-|\'|&#39;)*)/ig,
  "zionist": /(\bzion(?:\w|\-|\'|&#39;)*)/ig,
  "remainder": /(\bremain(?:\w|\-|\'|&#39;)*)/ig,
  "perverse": /(\bperver[st](?:\w|\-|\'|&#39;)*)/ig,
  "aufhebung": /(aufhebung(?:\w|\-|\'|&#39;)*)/ig,
  "perception": /((?:ap)perception)/ig,
  "the-other": /((?:[tT]he )?Other(?:\w|\-|\'|&#39;)*|(?:[Aa]n)?[oO]therness)/g,
  "precise-sense": /((?:in )?(?:\s?\w+ )?precise sense)/ig,
  "torture": /(\btortur(?:\w|\-|\'|&#39;)*)/ig,
  "very-beginning": /((?:in |from |since )?(?:its |the )very beginnings?)/ig,
  "order-of-being": /(\borders? of being)/ig,
  "the-real": /((?:[tT]he )?Real(?:\w|\-|\'|&#39;)*)/g,
  "reason": /((?:pure )reason(?!s)(?:\w|\-|\'|&#39;)*)/ig,
  "rational": / ((?:[\w\b\-]+)?rational(?:\w|\-|\'|&#39;)*)/ig,
  "phallus": /(\bphall[iu](?:\w|\-|\'|&#39;)*)/ig,
  "innocence": /(\binnocen(?:\w|\-|\'|&#39;)*)/ig,
  "very-heart": /((?:at the )?very (?:heart|core))/ig,
  "same-as": /((?:the )?same as)/ig,
  "son": /\b(son)\b/ig,
  "power": /((?:[\w\b\-]+)?power(?:\w|\-|\'|&#39;)*)/ig,
  "emergence": /(\bemerge(?!nc(?:y|ies))(?:\w|\-|\'|&#39;)*)/ig,
  "romantic": /((?:[\w\b\-]+)?roman[ct](?:\w|\-|\'|&#39;)*)/ig,
  "may-well": /((?:it |this |one |you |he |they |that |what )?(?:may |might )well(?: be)?(?: true)?)/ig,
  "time-to-time": /((?:from )?time to time)/ig,
  "pogrom": /(\bpogrom(?:\w|\-|\'|&#39;)*)/ig,
  "ghetto": /(\bghetto(?:\w|\-|\'|&#39;)*)/ig,
  "it-is-crucial": /((?:it |this |the )?(?:is )crucial(?: to| here)?)/ig,
  "price-to-be-paid": /((?:a |the )?price (?:\w+ )?(?:be )?paid)/ig,
  "the-gap-which-separates": /((?:a |the |that |this )?gaps? (?:between|(?:\w+ )?separat(?:\w|\-|\'|&#39;)*))/ig,
  "and-so-on": /(and so (?:on|forth))/ig,
  "ecological": /(\becolog(?:\w|\-|\'|&#39;)*)/ig,
  "logic": /(\blogics?(?:\w|\-|\'|&#39;)*)/ig,
  "blood": /(\bblood(?:\w|\-|\'|&#39;)*)/ig,
  "race": /(\bracial(?:ist)?|racis[tm])/ig,
  "repressed": /((?:return of )?(?:the )?repress(?:\w|\-|\'|&#39;)*)/ig,
  "part-of-no-part": /(parts?.of.no.part)/ig,
  "in-other-words": /(in other words)/ig,
  "the-only-way": /((?:the )?only ways?)/ig,
  "child": /(\bchild(?:ren)?(?:\w|\-|\'|&#39;)*)/ig,
  "absolute": /(\babsolut(?!ion)(?:\w|\-|\'|&#39;)*)/ig,
  "big-other": /((?:the )?big others?)/ig,
  "abstract": /((?:[\w\b\-]+)?abstract(?:\w|\-|\'|&#39;)*)/ig,
  "finance": /(\bfinanc(?:\w|\-|\'|&#39;)*)/ig,
  "unique": /((?:[\w\b\-]+)?unique(?:\w|\-|\'|&#39;)*)/ig,
  "proletariat": /(\bproletaria(?:\w|\-|\'|&#39;)*)/ig,
  "per-se": /(\bper se\b)/ig,
  "descartes": /((?:(?:ren[ée] )?descartes|cartesian)(?:\w|\-|\'|&#39;)*)/ig,
  "psychoanalysis": /(\bpsychoanaly(?:\w|\-|\'|&#39;)*)/ig,
  "balkan": /(\bbalkan(?:\w|\-|\'|&#39;)*)/ig,
  "boothby": /(\bboothby(?:\w|\-|\'|&#39;)*)/ig,
  "psychology": /(\bpsycholog(?:\w|\-|\'|&#39;)*)/ig,
  "evil": /(\bevil(?:\w|\-|\'|&#39;)*)/ig,
  "villain": /(\bvillain(?:\w|\-|\'|&#39;)*)/ig,
  "free": /((?:not |un\-)?free(?:doms?|s|ing|ly|d))/ig,
  "biopolitics": /(\bbiopoli(?:\w|\-|\'|&#39;)*)/ig,
  "infinite": /((?:in|\b)finit(?:\w|\-|\'|&#39;)*)/ig,
  "spinoza": /(\sspinoz(?:\w|\-|\'|&#39;)*)/ig,
  "political": /((?:the )?\bpolitic(?:\w|\-|\'|&#39;)*(?! correct))/ig,
  "politically-correct": /(\bpc\b|politically.correct)/g,
  "economic": /((?:the )?(?:[\w\b\-]+)?econom(?:\w|\-|\'|&#39;)*)/ig,
  "lamella": /(\blamella)/ig,
  "chaplin": /((?:charl.+?\b )?\bchaplin(?:\w|\-|\'|&#39;)*)/ig,
  "parody": /(\bparod(?:\w|\-|\'|&#39;)*)/ig,
  "grail": /((?:the )?(?:holy )?grail(?:\w|\-|\'|&#39;)*)/ig,
  "giovanni": /((?:don )giovanni(?:\w|\-|\'|&#39;)*)/ig,
  "kierkegaard": /((?:[\w\b\-]+)?kierkegaard(?:\w|\-|\'|&#39;)*)/ig,
  "mozart": /(\bmozart(?:\w|\-|\'|&#39;)*)/ig,
  "magic-flute": /((?:the )?magic flute)/ig,
  "chauvinist": /((?:male )?(?:[\w\b\-]+)?chauvinis(?:\w|\-|\'|&#39;)*)/ig,
  "paradox": /((?:a |the |that |this )?paradox(?:\w|\-|\'|&#39;)*)/ig,
  "symbolic-order": /((?:a |the |that |this )?symbolic order(?:\w|\-|\'|&#39;)*)/ig,
  "symbolic": /((?:[\w\b\-]+)?symbol(?:\w|\-|\'|&#39;)*(?!.order))/ig,
  "universal": /((?:the )?(?:[\w\b\-]+)?universal(?:\w|\-|\'|&#39;)*)/ig,
  "individual": /((?:the )?(?:[\w\b\-]+)?individua(?:\w|\-|\'|&#39;)*)/ig,
  "particular": /((?:the )?(?:[\w\b\-]+)?particular(?:\w|\-|\'|&#39;)*)/ig,
  "eternal": /((?:the )?(?:[\w\b\-]+)?etern(?:al|it)(?:\w|\-|\'|&#39;)*)/ig,
  "horror": /(\bhorr(?:ors?|if)(?:\w|\-|\'|&#39;)*)/ig,
  "data": /(\bdat(?:a|um))/ig,
  "symptom": /((?:the |these |that )?(?:[\w\b\-]+)?symptom(?:\w|\-|\'|&#39;)*)/ig,
  "prohibition": /(\bprohib(?:\w|\-|\'|&#39;)*)/ig,
  "negation": /(\bnegat(?:\w|\-|\'|&#39;)*)/ig,
  "positivity": /(\bpositiv(?:\w|\-|\'|&#39;)*)/ig,
  "materialist": /((?:[\w\b\-]+)?materialis(?:\w|\-|\'|&#39;)*)/ig,
  "trauma": /(\btrauma(?:\w|\-|\'|&#39;)*)/ig,
  "recognition": /(\brecogni(?:\w|\-|\'|&#39;)*)/ig,
  "magic": /((?:the )?magic(?:\w|\-|\'|&#39;)*)/ig,
  "the-social": /((?:the )?social)(?!\w)/ig,
  "society": /(\bsociet(?:\w|\-|\'|&#39;)*)/ig,
  "mask": /(\bmask(?:\w|\-|\'|&#39;)*)/ig,
  "face": /(\bfac(?:ial|e)(?:\w|\-|\'|&#39;)*)/ig,
  "neighbor": /(\bneighbou?r(?:\w|\-|\'|&#39;)*)/ig,
  // "the-human": /(the human)(?!\w)/ig,
  "his-or-her": /(his or her)/ig,
  "kennedy": /(JFK|kennedy)/ig,
  "dominance": /(\bdomina[nt](?:\w|\-|\'|&#39;)*)/ig,
  "in-this-sense": /(in this sense)/ig,
  "way-of-life": /(ways? of (?:life|living)|life.?style(?:\w|\-|\'|&#39;)*)/ig,
  "more-and-more": /(more and more)/ig,
  "relationship-between": /((?:a |the |that |this |in )?(?:\brelat|link)(?:\w|\-|\'|&#39;)*(?:\s?\w+ )? ?(?:between|among|to)?)/ig,
  "objet-petit-a": /((?:[Oo]bjets?|[Oo]bjects?)(?: [Pp]etit| [Ss]mall)?(?: a)?)/g,
  "bourgeois": /((?:petit )?bourgeoi(?:\w|\-|\'|&#39;)*)/ig,
  "in-both-cases": /(in (?:all |both |these |this |that |every )cases?)/ig,
  "at-its-purest": /(at its purest)/ig,
  "illusion": /(\billus(?:or|io|o)(?:\w|\-|\'|&#39;)*)/ig,
  "first-thing": /((?:the )?first thing)/ig,
  "in-the-middle": /(in the (?:middle|midst))/ig,
  "antinomy": /(\bantinom(?:\w|\-|\'|&#39;)*)/ig,
  "majority": /(\bmajorit(?:\w|\-|\'|&#39;)*)/ig,
  "minority": /((?:[\w\b\-]+)?minorit(?:\w|\-|\'|&#39;)*(?! report))/ig,
  "minority-report": /(minority reports?)/ig,
  "antagonism": /((?:[\w\b\-]+)?antagon(?:\w|\-|\'|&#39;)*)/ig,
  "again-and-again": /(again and again)/ig,
  "example": /((?:for |as an |as |few |some |these )?examples?)/ig,
  "communist": /((?:[\w\b\-]+)?communi(?!t|c)(?:\w|\-|\'|&#39;)*)/ig,
  "community": /((?:[\w\b\-]+)?communit(?:\w|\-|\'|&#39;)*)/ig,
  "communication": /((?:[\w\b\-]+)?communicat(?:\w|\-|\'|&#39;)*)/ig,
  "destroy": /((?:[\w\b\-]+)?destr(?:uct|oy)(?:\w|\-|\'|&#39;)*)/ig,
  "fascist": /((?:[\w\b\-]+)?fasci(?!na)(?:\w|\-|\'|&#39;)*)/ig,
  "socialist": /((?:[\w\b\-]+)?socialis(?:\w|\-|\'|&#39;)*)/ig,
  "enlightened": /((?:[\w\b\-]+)?enlighten(?:\w|\-|\'|&#39;)*)/ig,
  "existence": /(\bexisten(?:\w|\-|\'|&#39;)*)/ig,
  "paraphrase": /((?:to )?paraphras(?:\w|\-|\'|&#39;)*)/ig,
  "really-existing": /(really.existing.(\w+?\b))/ig,
  "male": /(\bmale[s]\b|masculin(?:\w|\-|\'|&#39;)*)/ig,
  "female": /(\bfemale[s]\b|feminin(?:\w|\-|\'|&#39;)*|femme fatales?|(?:[\w\b\-]+)?wom[ea]n(?:\w|\-|\'|&#39;)*)/ig,
  "bureaucracy": /((?:[\w\b\-]+)?bureaucra(?:\w|\-|\'|&#39;)*)/ig,
  "leftist": /(\b[Ll]efts?(?:ists?))/g,
  "sublime": /((?:the )?sublime)/ig,
  "dissident": /(\bdiss(?:ent|iden)(?:\w|\-|\'|&#39;)*)/ig,
  "identity": /((?:[\w\b\-]+)?identit(?:\w|\-|\'|&#39;)*)/ig,
  "the-subject": /((?:the )?(?:[\w\b\-]+)?subject(?:\w|\-|\'|&#39;)*)/ig,
  "substance": /(\b(?:de|un)?substan[ct](?:\w|\-|\'|&#39;)*)/ig,
  "ambiguity": /((?:[\w\b\-]+)?ambigu(?:\w|\-|\'|&#39;)*)/ig,
  "castration": /((?:[\w\b\-]+)?castrat(?:\w|\-|\'|&#39;)*)/ig,
  "boy": /(boy(?:\w|\-|\'|&#39;)*)/ig,
  "girl": /(girl(?:\w|\-|\'|&#39;)*)/ig,
  "maiden": /(\bmaiden(?:\w|\-|\'|&#39;)*)/ig,
  "virgin": /(\bvirgin(?:\w|\-|\'|&#39;)*)/ig,
  "woman": /(\bwom[ae]n(?:\w|\-|\'|&#39;)*)/ig,
  "vagina": /(\bvagina(?:\w|\-|\'|&#39;)*)/ig,
  "a-priori": /(a priori)/ig,
  "spirit": /(\bspirit(?:\w|\-|\'|&#39;)*)/ig,
  "distortion": /((?:[\w\b\-]+)?distort(?:\w|\-|\'|&#39;)*)/ig,
  "antisemitism": /(anti.?semit(?:\w|\-|\'|&#39;)*)/ig,
  "human": /((?:[\w\b\-]+)?human(?!e)(?:\w|\-|\'|&#39;)*)/ig,
  "oedipus": /((?:[\w\b\-]+)?oedip(?:\w|\-|\'|&#39;)*)/ig,
  "theory": /(\btheor(?:\w|\-|\'|&#39;)*)/ig,
  "paradigm": /((?:[\w\b\-]+)?paradigm(?:[\w\b\-]+)?)/ig,
  "ethical": /((?:[\w\b\-]+)?ethic(?:\w|\-|\'|&#39;)*)/ig,
  "ethnic": /((?:[\w\b\-]+)?ethnic(?:\w|\-|\'|&#39;)*)/ig,
  "opposite": /(\boppos(?!ition)(?:\w|\-|\'|&#39;)*)/ig,
  "posited": /(\bposit(?:\b|s|ed))/ig,
  "position": /(\bposition(?:\w|\-|\'|&#39;)*)/ig,
  "the-west": /(the west\b|(?:the )?western)(?! europe)/ig, // Add West (case-sensitive)?
  "the-east": /(the east\b|(?:the )?eastern)(?! europe)/ig, // Add East (case-sensitive)?
  "fate": /(\bfate(?:\w|\-|\'|&#39;)*)/ig,
  "opera": /(\bopera(?:\w|\'|&#39;)*)/ig,
  "asian": /(\basians?)/ig,
  "dream": /(dream(?:\w|\-|\'|&#39;)*)/ig,
  "progressive": /((?:[\w\b\-]+)?progressiv(?:\w|\-|\'|&#39;)*)/ig,
  "poor": /(the poor(?:\w|\-|\'|&#39;)*)/ig,
  "rich": /(the rich(?:\w|\-|\'|&#39;)*)/ig,
  "thesis": /((?:[\w\b\-]+)?thes[ie]s)/ig,
  "corrupt": /((?:[\w\b\-]+)?corrupt(?:\w|\-|\'|&#39;)*)/ig,
  "partisan": /((?:[\w\b\-]+)?partisan(?:\w|\-|\'|&#39;)*)/ig,
  "barred-s": /(\$)/ig,
  "symmetry": /(a?symmetr(?:\w|\-|\'|&#39;)*)/ig,
  "moral": /((?:a|im)moral(?!es)(?:\w|\-|\'|&#39;)*)/ig,
  "badiou": /(badiou(?:\w|\-|\'|&#39;)*)/ig,
  "plato": /((?:[\w\b\-]+)?plato(?:\w|\-|\'|&#39;)*)/ig,
  "aristotle": /((?:[\w\b\-]+)?aristotle(?:\w|\-|\'|&#39;)*)/ig,
  "jacobin": /(jacobin(?:\w|\-|\'|&#39;)*)/ig,
  "odradek": /(odradek(?:\w|\-|\'|&#39;)*)/ig,
  "hardt-negri": /(hardt|negri|hardt.negri)/ig,
  "china": /(chin(?:a|ese))/ig,
  "japan": /(japan(?:\w|\-|\'|&#39;)*)/ig,
  "korea": /((?:north |south )korea(?:\w|\-|\'|&#39;)*)/ig,
  "singapore": /(singapore(?:\w|\-|\'|&#39;)*)/ig,
  "tibet": /(tibet(?:\w|\-|\'|&#39;)*)/ig,
  "buddhism": /(buddh(?:a|is)(?:\w|\-|\'|&#39;)*)/ig,
  "nietzsche": /(nietzsche(?:\w|\-|\'|&#39;)*)/ig,
  "foucalt": /(foucalt(?:\w|\-|\'|&#39;)*)/ig,
  "derrida": /(derrid[ea](?:\w|\-|\'|&#39;)*)/ig,
  "legal": /((?:il)?legal(?:\w|\-|\'|&#39;)*)/ig,
  "greece": /(greece|greeks?)/ig,
  "cuba": /(\bcuban?(?:\w|\-|\'|&#39;)*)/ig,
  "hate": /(\b(?:hate|hatred)(?:\w|\-|\'|&#39;)*)/ig,
  "kernel": /((?:the )?(?:true |real |precise |very )?kernel)/ig,
  "continental": /(\bcontinental)/ig,
  "nationalism": /(\bnationalis[tm](?:\w|\-|\'|&#39;)*)/ig,
  "ontic": /(\bontic(?:\w|\-|\'|&#39;)*)/ig,
  "cause": /(\bCauses?)/g,
  "secret": /(\bsecret(?!e)(?:\w|\-|\'|&#39;)*)/ig,
  "europe": /((?:eastern |western )europe(?:\w|\-|\'|&#39;)*)/ig,
  "nazi": /((?:nazi|(?:the )?third reich)(?:\w|\-|\'|&#39;)*)/ig,
  "world-war": /((?:the )?(?:\s?\w+?\b )?world war)/ig,
  "worker": /((?:the )?worker(?:\w|\-|\'|&#39;)*)/ig,
  "hitler": /((?:mr.+? |mister |adolph |heil )hitler(?:\w|\-|\'|&#39;)*)/ig,
  "nuclear": /(nuclear|nukes?)/ig,
  "surplus": /(surplus(?:\w|\-|\'|&#39;)*)/ig,
  "police": /((?:the )?police(?: officers?)?(?:\w|\-|\'|&#39;)*)/ig,
  "wall-street": /(wall st(?:reet|\.)?)/ig,
  "privilege": /(privilege(?:\w|\-|\'|&#39;)*)/ig,
  "etcetera": /(etcetera|et cetera|et c|etc\.? )/ig,
  "robot": /(robot(?:\w|\-|\'|&#39;)*)/ig,
  "machine": /((?:machine|mechanical)(?:\w|\-|\'|&#39;)*)/ig,
  "student": /(student(?:\w|\-|\'|&#39;)*)/ig,
  "professor": /(professor(?:\w|\-|\'|&#39;)*)/ig,
  "academic": /((?:[\w\b\-]+)?academi(?:\w|\-|\'|&#39;)*)/ig,
  "liberal": /((?:[\w\b\-]+)?liberal(?:\w|\-|\'|&#39;)*)/ig,
  "school": /(school(?:\w|\-|\'|&#39;)*)/ig,
  "university": /(universit(?:\w|\-|\'|&#39;)*)/ig,
  "intellectual": /((?:[\w\b\-]+)?intellectual(?:\w|\-|\'|&#39;)*)/ig,
  "philosophy": /((?:[\w\b\-]+)?philosoph(?:\w|\-|\'|&#39;)*)/ig,
  "love": /((?:[\w\b\-]+)?(?:love|loving)(?:\w|\-|\'|&#39;)*)/ig,
  "ontology": /((?:[\w\b\-]+)?ontolog(?:\w|\-|\'|&#39;)*)/ig,
  "final": /((?:[\w\b\-]+)?final(?!ly)(?:\w|\-|\'|&#39;)*)/ig,
  "ideal": /((?:[\w\b\-]+)?ideal(?:s|is)?(?:\w|\-|\'|&#39;)*)/ig,
  "idea": /(\bideas?\b)/ig,
  "consequence": /((?:[\w\b\-]+)?consequen(?:\w|\-|\'|&#39;)*)/ig,
  "cognition": /(\bcognit(?:ion|ive map)(?:\w|\-|\'|&#39;)*)/ig,
  "animal": /(\banimal(?:\w|\-|\'|&#39;)*)/ig,
  "structure": /((?:[\w\b\-]+)?structur(?:\w|\-|\'|&#39;)*)/ig,
  "system": /(\bsystem(?:\w|\-|\'|&#39;)*)/ig,
  "fundamental": /((?:[\w\b\-]+)?fundamental(?:\w|\-|\'|&#39;)*)/ig,
  "violence": /((?:[\w\b\-]+)?violen(?:\w|\-|\'|&#39;)*)/ig,
  "understand": /((?:[\w\b\-]+)?understand(?:\w|\-|\'|&#39;)*)/ig,
  "orthodox": /((?:[\w\b\-]+)?orthodox(?:\w|\-|\'|&#39;)*)/ig,
  "foundation": /(\bfoundation(?:\w|\-|\'|&#39;)*)/ig,
  "public": /(\npublic(?:\w|\-|\'|&#39;)*)/ig,
  "private": /(\npriva(?:te|c)(?:\w|\-|\'|&#39;)*)/ig,
  "evolution": /(\bevol[uv](?:\w|\-|\'|&#39;)*)/ig,
  "reproduction": /(reproduc(?:\w|\-|\'|&#39;)*)/ig,
  "produce": /(\bproduc[te](?!i)(?:\w|\-|\'|&#39;)*)/ig,
  "transfer": /((?:[\w\b\-]+)?transfer(?:\w|\-|\'|&#39;)*)/ig,
  "production": /(\bproducti(?:on|vit)(?:\w|\-|\'|&#39;)*)/ig,
  "money": /(\bmoney)/ig,
  "ultimate": /(\bultimate(?!ly)(?:\w|\-|\'|&#39;)*?)/ig,
  "robespierre": /(\brobespierre(?:\w|\-|\'|&#39;)*?)/ig,
  "battle": /(\bbattl[ie](?:\w|\-|\'|&#39;)*?)/ig,
  "contingent": /((?:[\w\b\-]+)?contingen(?:\w|\-|\'|&#39;)*)/ig,
  //"america": /((?!south.|central.|latin.)america(?:\w|\-|\'|&#39;)*|united states)/ig,
  "enemy": /((?:the |our |his |her |this |that |their |my |your |one(?:\'|&#39;)s |other(?:\'|&#39;)s )?\benem[yi](?:\w|\-|\'|&#39;)*)/ig,
  "hero": /(\bhero(?:\w|\-|\'|&#39;)*)/ig,
  "in-fact": /((?:in|the) facts?)(?!\w)/ig,
  "revolutionary-terror": /(revolutionary terrors?)/ig,
  "definition": /(by definition)/ig,
  "alien": /(alien(?:\w|\-|\'|&#39;)*)/ig,
  "foreign": /(foreign(?:\w|\-|\'|&#39;)*)/ig,
  "stricto-sensu": /(stricto sensu)/ig,
  "minimal-difference": /(minimal differences?)/ig,
  "death": /((?:between )?(?:the )?(?:two )?(?:[\w\b\-]+)?(?:deaths?|dead|\bdie|\bdyin)(?:\w|\-|\'|&#39;)*)/ig,
  "death-drive": /((?:the )?(?:death drives?|trieb))/ig,
  "master-signifier": /(master.signifiers?)/ig,
  "the-master": /((?:the )?(?:discourse of )?(?:the )?master(?!f|w|p|.signif)(?:(?:\'|&#39;)s discourse)?)/ig,
  "signified": /((?:[\w\b\-]+)?signif(?:y|ie[sd])(?:\w|\-|\'|&#39;)*)/ig,
  "short-circuit": /(short circuit(?:\w|\-|\'|&#39;)*)/ig,
  "transcendental": /(transcenden(?:\w|\-|\'|&#39;)*)/ig,
  "dasein": /(dasein(?:\w|\-|\'|&#39;)*)/ig,
  "embodiment": /((?:[\w\b\-]+)?embod[iy](?:\w|\-|\'|&#39;)*)/ig,
  "mathilda": /(mathilda(?:\w|\-|\'|&#39;)*)/ig,
  "paul": /(paul(?:\w|\-|\'|&#39;)*)/ig,
  "reduction": /((?:ir)?reduc(?:\w|\-|\'|&#39;)*)/ig,
  "paternal": /(patern[ai](?:\w|\-|\'|&#39;)*)/ig,
  "maternal": /(matern[ai](?:\w|\-|\'|&#39;)*)/ig,
  "primordial": /(primordial(?:\w|\-|\'|&#39;)*)/ig,
  "sex": /((?:[\w\b\-]+)?sex(?:\w|\-|\'|&#39;)*)/ig,
  "apropos": /(\bapropos)/ig,
  "noumenal": /((?:[\w\b\-]+)?noumen(?:\w|\-|\'|&#39;)*)/ig,
  "feminist": /((?:[\w\b\-]+)?feminis(?:\w|\-|\'|&#39;)*)/ig,
  "construct": /((?:de)?construc(?:\w|\-|\'|&#39;)*)/ig,
  "consciousness": /((?:self.)?consciousness)/ig,
  "self": /(Self(?:\'s|&#39;s|s)?(?!.?consciousness))/g,
  "technology": /((?:techno|technical(?!ly))(?:\w|\-|\'|&#39;)*)/ig,
  "knowledge": /(\b(?:knowledge|supposed to know)(?:\w|\-|\'|&#39;)*)/ig,
  "modality": /(\bmodalit(?:\w|\-|\'|&#39;)*)/ig,
  "supposition": /((?:pre)?supposi[tn](?:\w|\-|\'|&#39;)*)/ig,
  "suffice-it-to": /(suffice(?: it)? to (?:\w+?\b)?)/ig,
  "unknown": /(unknow(?:\w|\'|&#39;)*)/ig,
  "soviet": /(soviets?)/ig,
  "possible": /((?:the |this |that )?(?:\bvery )?(?:im)?possibi?l(?:\w|\-|\'|&#39;)*)/ig,
  "union": /(union(?:\w|\-|\'|&#39;)*)/ig,
  "stalin": /(stalin(?:is[tm]s?)?)/ig,
  "lenin": /(lenin(?:is[tm]s?)?)/ig,
  "marx": /(marx(?! bro)(?:is[tm]s?)?)/ig,
  "marx-brothers": /((?:the )?marx brot(?:\w|\-|\'|&#39;)*)/ig,
  "the-matrix": /(the matrix|(?:the )?matrix(?: reloaded| revolutions?| trilogy| films?))/ig,
  "blade-runner": /(blade runner)/ig,
  "noir": /(noirs?)/ig,
  "jameson": /(jameson(?:ian)?)/ig,
  "normal": /(normal(?:\w|\-|\'|&#39;)*)/ig,
  "labor": /([^eE]labou?r)/ig,
  "immanent": /(\bimmanen(?:\w|\-|\'|&#39;)*)/ig,
  "commodity": /(\bcommoditi(?:\w|\-|\'|&#39;)*)/ig,
  "fetish": /(\bfetish(?:\w|\-|\'|&#39;)*)/ig,
  "value": /(\bvalue(?:\w|\-|\'|&#39;)*)/ig,
  "irreducible": /(\birreduc(?:\w|\-|\'|&#39;)*)/ig,
  "reference": /(\breferen(?:\w|\-|\'|&#39;)*)/ig,
  "zeitgeist": /(zeitgeist)/ig,
  "object": /(\bobject(?! small|iv)(?:\w|\-|\'|&#39;)*)/ig,
  "reflection": /((?:[\w\b\-]+)?reflect(?:\w|\-|\'|&#39;)*)/ig,
  "objective": /((?:objectiv|empirical)(?:\w|\-|\'|&#39;)*)/ig,
  "synthesis": /(synthesi(?:\w|\-|\'|&#39;)*)/ig,
  "slave": /(slave(?:\w|\-|\'|&#39;)*)/ig,
  "imperial": /(imperial(?:\w|\-|\'|&#39;)*|empires?)/ig,
  "categorical-imperative": /(categorical.imperative)/ig,
  "dictator": /(dictator(?:\w|\-|\'|&#39;)*)/ig,
  "tautology": /(\btautolog(?:\w|\-|\'|&#39;)*)/ig,
  "teleology": /((?:[\w\b\-]+)?teleolog(?:\w|\'|&#39;)*)/ig,
  "semiotic": /(\bsemio[st](?:\w|\-|\'|&#39;)*)/ig,
  "triad": /((?:this |that |the |basic )?triads?)/ig,
  "gesture": /(gestur(?:\w|\-|\'|&#39;)*)/ig,
  "visible": /((?:[\w\b\-]+)?[^i]visib(?:\w|\-|\'|&#39;)*)/ig,
  "intent": /((?:[\w\b\-]+)?(?:[^n][^t])inten(?:\w|\-|\'|&#39;)*)/ig,
  "event": /(Event(?:al|s)?)/g,
  "law": /(\blaw(?:\w|\-|\'|&#39;)*)/ig,
  "libido": /(\blibid(?:[\w\b\-]+)?)/ig,
  "happy": /((?:[\w\b\-]+)?shapp[iy](?:\w|\-|\'|&#39;)*)/ig,
  "transition": /(transit[io](?:\w|\-|\'|&#39;)*)/ig,
  "recall": /((?:recall|recollect)(?:\w|\-|\'|&#39;)*)/ig,
  "interrupt": /((?:un)?interrupt(?:\w|\-|\'|&#39;)*)/ig,
  "movement": /(\bmovement(?:\w|\-|\'|&#39;)*)/ig,
  "religion": /(\breligi(?:\w|\-|\'|&#39;)*)/ig,
  "moment": /((?:the )?(?:very |precise |exact |same )?\bmoment(?:\w|\-|\'|&#39;)*)/ig,
  "barbarism": /(\bbarbari(?:\w|\-|\'|&#39;)*)/ig,
  "horizon": /(\bhorizons?)/ig,
  "bible": /((?:the )?(?:\bscripture|\bbibl(?:e|ical)|(?:new|old) testament))/ig,
  "x": /(X)/g,
  "enunciation": /((?:the |this )?(?:un)?enuncia(?:\w|\-|\'|&#39;)*)/ig,
  "authority": /((?:[\w\b\-]+)?authorit(?:y|ie|arian)(?:\w|\-|\'|&#39;)*)/ig,
  "authentic": /((?:authentic|genuine)(?:\w|\-|\'|&#39;)*)/ig,
  "parsifal": /(parsifal(?:\w|\-|\'|&#39;)*)/ig,
  "excess": /(excess(?:\w|\-|\'|&#39;)*)/ig,
  "wagner": /(wagner(?:(?:\'|&#39;)s|ian)?)/ig,
  "althusser": /(althusser(?:\w|\-|\'|&#39;)*)/ig,
  "prison": /((?:[\w\b\-]+)?prison(?:\w|\-|\'|&#39;)*)/ig,
  "africa": /(\bafrica(?:\w|\-|\'|&#39;)*)/ig,
  "tradition": /(\btradition(?:\w|\-|\'|&#39;)*)/ig,
  "belief": /((?:[\w\b\-]+)?belie[fv](?:\w|\-|\'|&#39;)*)/ig,
  "levi-strauss": /((?:claude )?lévi-strauss(?:\w|\-|\'|&#39;)*)/ig,
  "lynch": /(\bLynch(?:\w|\-|\'|&#39;)*)/g,
  "kafka": /((?:[\w\b\-]+)?kafka(?:\w|\'|&#39;)*)/ig,
  "brazil": /(\bbrazil(?:\w|\'|&#39;)*)/ig,
  "hitchcock": /((?:[\w\b\-]+)?hitchcock(?:\w|\-|\'|&#39;)*)/ig,
  "christ": /((?:jesus )?(?:christ|jesus)(?!ian|mas)(?:\-like| jesus|.figure|(?:\'|&#39;)s?)?)/ig,
  "christian": /((?:[\w\b\-]+)?christian(?:\w|\'|&#39;)*)/ig,
  "civil": /(\b(?:civil|civili[sz]ation|civili[sz]ed)\b)/ig,
  "yugoslavia": /((?:[\w\b\-]+)?yugoslav(?:\w|\'|&#39;)*)/ig,
  "syria": /(\bsyria(?:\w|\-|\'|&#39;)*)/ig,
  "pakistan": /(\bpakistan(?:\w|\-|\'|&#39;)*)/ig,
  "egypt": /(\begypt(?:\w|\-|\'|&#39;)*)/ig,
  "murder": /((?:\bmurder|\bkill)(?:\w|\-|\'|&#39;)*)/ig,
  "lebanon": /(leban(?:on|ese)(?:\w|\-|\'|&#39;)*)/ig,
  "country": /(countr(?:y|ie)(?:\w|\-|\'|&#39;)*)/ig,
  "gay": /((?:lesbian|\bgay|homo.?sexual|same.?sex)(?:\w|\-|\'|&#39;)*)/ig,
  "god": /(God(?:dess)?(?:(?:\'|&#39;)?s?|-like|-king))/g,
  "class": /((?:[\w\b\-]+)?class(?!ic|\=)(?:\w|\-|\'|&#39;)*)/ig,
  "global": /((?:[\w\b\-]+)?global(?:\w|\-|\'|&#39;)*)(?! capital)/ig,
  "secular": /((?:[\w\b\-]+)?secular(?:\w|\-|\'|&#39;)*)/ig,
  "independent": /((?:[\w\b\-]+)?independen(?:\w|\-|\'|&#39;)*)/ig,
  "ideology": /((?:[\w\b\-]+)?ideolog(?:\w|\-|\'|&#39;)*)/ig,
  "capital": /((?:global |late )?(?:[\w\b\-]+)?capital(?:\w|\-|\'|&#39;)*)/ig,
  "superego": /(superego(?: injunction)?(?:\w|\-|\'|&#39;)*)/ig,
  "thanatos": /(thanatos)/ig,
  "muhammad": /((?:the )?(?:prophet )?muhammad(?:\w|\'|&#39;)*)/ig,
  "in-effect": /(in effect)/ig,
  "disturb": /(disturb(?:\w|\-|\'|&#39;)*)/ig,
  "aggression": /(aggress(?:\w|\-|\'|&#39;)*)/ig,
  "supplement": /(supplement(?:\w|\-|\'|&#39;)*)/ig,
  "conflict": /(conflict(?:\w|\-|\'|&#39;)*)/ig,
  "messiah": /((?:[\w\b\-]+)?messia(?:\w|\-|\'|&#39;)*)/ig,
  "theology": /((?:[\w\b\-]+)?theolog(?:\w|\-|\'|&#39;)*)/ig,
  "automaton": /(automat(?:a|on)(?:\w|\-|\'|&#39;)*)/ig,
  "hidden": /((?:[\w\b\-]+)?hidden)/ig,
  "blind": /((?:[\w\b\-]+)?blind(?:\w|\-|\'|&#39;)*)/ig,
  "redemption": /((?:redeem|redemp)(?:\w|\-|\'|&#39;)*)/ig,
  "hysterical": /((?:the )?\bhysteric(?:\w|\-|\'|&#39;)*(?: patient)?)/ig,
  "hamas": /(\bhamas\b)/ig,
  "darwin": /((?:[\w\b\-]+)?darwin(?:\w|\-|\'|&#39;)*)/ig,
  "al-qaeda": /((?:al.)?qaeda)/ig,
  "saddam": /((?:saddam|hussein|saddam hussein)(?:\w|\'|&#39;)*)/ig,
  "modern": /((?:[\w\b\-]+)?modern(?:\w|\-|\'|&#39;)*)/ig,
  "imagination": /((?:[\w\b\-]+)?imagin(?:\w|\'|&#39;)*)/ig,
  "fantasy": /((?:ph|f)antas(?:\w|\'|&#39;)*)/ig,
  "narcissism": /((?:[\w\b\-]+)?narciss(?:\w|\'|&#39;)*)/ig,
  "place-of-worship": /((?:mosque|temple|synagog|church|cathedral)(?:\w|\'|&#39;)*)/ig,
  "worship": /((?:[\w\b\-]+)?worship(?:\w|\'|&#39;)*)/ig,
  "pleasure-principle": /((?:beyond )?(?:the )?pleasure principle)/ig,
  "jouissance": /((?:[\w\b\-]+)?jouissance)/ig,
  "history": /((?:[\w\b\-]+)?histor(?:\w|\-|\'|&#39;)*)/ig,
  "mother": /\b(mother(?:\w|\-|\'|&#39;)*)/ig,
  "father": /((?:[\w\b\-]+)?father(?:\w|\-|\'|&#39;)*)/ig,
  "analysand": /(analysands?)/ig,
  "anxiety": /(anxi(?:ety|ous))/ig,
  "jew": /((?:[\w\b\-]+)?jew(?!el)(?:\w|\-|\'|&#39;)*)/ig,
  "judaism": /(judai(?:\w|\-|\'|&#39;)*)/ig,
  "shoah": /(\bshoah)/ig,
  "divine": /(\bdivin(?:\w|\-|\'|&#39;)*)/ig,
  "practice": /(\bpractice(?:\w|\-|\'|&#39;)*)/ig,
  "personal": /((?:im)?personal(?!it)(?:\w|\-|\'|&#39;)*)/ig,
  "libertarian": /((?:[\w\b\-]+)?libertar(?:\w|\'|&#39;)*)/ig,
  "holocaust": /(holocaust)/ig,
  "disowned": /(\bdis(?:own|avow)(?:\w|\-|\'|&#39;)*)/ig,
  "afghanistan": /(afghan(?:\w|\-|\'|&#39;)*)/ig,
  "iraq": /(iraq(?:\w|\-|\'|&#39;)*)/ig,
  "iran": /(iran(?:\w|\-|\'|&#39;)*)/ig,
  "india": /(india(?:\w|\-|\'|&#39;)*)/ig,
  "native": /(nativ(?:\w|\-|\'|&#39;)*)/ig,
  "israel": /((?:[\w\b\-]+)?israel(?:\w|\-|\'|&#39;)*)/ig,
  "islam": /(islam(?!o)(?:\w|\-|\'|&#39;)*)/ig,
  "muslim": /(muslim(?:\w|\-|\'|&#39;)*)/ig,
  "palestine": /(palestin(?:\w|\-|\'|&#39;)*)/ig,
  "jerusalem": /(jerusalem(?:\w|\-|\'|&#39;)*)/ig,
};


module.exports.keys = zizekKeys;